spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "3.0"

accounts:
  message: "Welcome to accounts related prod APIs "
  contactDetails:
    name: "Product Owner"
    email: "123@example.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384

localization:
  header: "The test header from YML file for 'test' server"
  message: "Welcome to test app related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@doe.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
