spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to accounts related QA APIs "
  contactDetails:
    name: "Product Owner"
    email: "123@example.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371

localization:
  header: "The test header from YML file for 'test' server"
  message: "Welcome to test app related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@doe.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
